### ISSUE TITLE
Unable to share template if I use postgres as data store.

### ISSUE THREAD

**Issue by jsskarthik1** [jsreport/jsreport-postgres-store#5]
Getting the following error.

`2018-10-09T09:37:47.233Z - error: Error during processing request at http://0.0.0.0:5488/api/templates/sharing/SyCSPaO5X/access/read, details: AssertionError [ERR_ASSERTION]: Error while trying to add a non-existant node to a query
    at constructor.Node.add (/app/node_modules/sql/lib/node/index.js:17:3)
    at constructor.Node.addAll (/app/node_modules/sql/lib/node/index.js:74:10)
    at constructor.select (/app/node_modules/sql/lib/node/query.js:92:12)
    at Table.select (/app/node_modules/sql/lib/table.js:180:18)
    at module.exports (/app/node_modules/odata-to-sql/lib/query.js:20:34)
    at Object.query (/app/node_modules/odata-to-sql/lib/transformer.js:42:14)
    at Cursor.toArray (/app/node_modules/jsreport-sql-store/lib/sqlProvider.js:21:29)
    at replay (/app/node_modules/jsreport-core/lib/store/collection.js:58:21)
    at listenerPromise.then (/app/node_modules/jsreport-core/lib/store/collection.js:65:50)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:432:57)`

**Comment by jsskarthik1** [comment]
This seems to be a bug with jsreport-public-template. I'll post it over there. You can follow up here: https://github.com/jsreport/jsreport-public-templates/issues/2#issue-368149870
